# Generated by Django 6.0.5 on 2026-05-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orders_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
