# Generated by Django 6.0.5 on 2026-05-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
