# Generated by Django 6.0.5 on 2026-05-31 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_created',
            new_name='date_ordered',
        ),
    ]
