# Generated by Django 6.0.5 on 2026-06-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
